services:
  server:
    image: luongld123zinza/chat-server:latest
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
    restart: unless-stopped

  client:
    image: luongld123zinza/chat-client:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    depends_on:
      - server
